### ISSUE TITLE
add a timer / hide the configuration information

### ISSUE THREAD

**Issue by axel584** [Bkoos/EMDR-for-browsers#2]
Your app is very nice.
Could you add a timer to launch the EMDR for 20 seconde (or 1 minute) ? 
Could you add a icon to hide (and show) the configuration tools) ?

Thank you very much,

Axel

**Comment by hosteren** [comment]
Thanks for the high praise. I've added a timer as another slider, that can be set from 0 (business as usual) to 10 minutes. The settings can be hidden, and the new settings are saved in localStorage like the others.
